--comando de criação de banco de dados
CREATE DATABASE ALUNO_SENAI

--acessar  objetos contidos no banco de dados
SELECT* FROM ALUNO_SENAI.SYS.ALL_COLUMNS

SELECT* FROM AdventureWorks2017.SYS.ALL_COLUMNS

SELECT*FROM.SYS.OBJECTS;

SELECT*FROM.SYS.OBJECTS;

EXEC SP_HELPDB;

EXEC SP_HELPDB ALUNO_SENAI;

SELECT DB_NAME();

EXEC SP_SPACEUSED;

USE AdventureWorks2017
--TABELAS DE SISTEMA
--Armazena todos os objetos do banco de dados
SELECT * FROM.SYSOBJECTS

--Tabelas de usuarios
SELECT * FROM.SYSOBJECTS WHERE XTYPE = 'U'
--Chaves primarias
SELECT * FROM.SYSOBJECTS WHERE XTYPE = 'PK'

--Tabelas e suas primarias
SELECT T.NAME AS TABELA, PK.NAME AS CHAVE_PRIMARIA
FROM SYSOBJECTS T JOIN SYSOBJECTS PK ON T.id = PK.parent_obj
WHERE T.xtype = 'U'

--VIEWS DE CATALAGO
--TABELA DE USUARIO
SELECT * FROM SYS.TABLES
--COLUNAS DE UMA TABELA
SELECT * FROM SYS.COLUMNS
--TIPOS DE DADOS
SELECT * FROM SYS.TYPES
--INDICES
SELECT *FROM SYS.INDEXES
--CAMPOS IDENTIDADE
SELECT * FROM SYS.IDENTITY_COLUMNS
--CHAVE UNICAS E CHAVES PRIMARIAS
SELECT * FROM SYS.KEY_CONSTRAINTS


SELECT nome,idade
FROM
clientes
WHERE

INSERT INTO produtos (nome,preço)
VALUES ('Notebook;1500.000)

cidade = São Paulo;





